# Generated by Django 3.1.3 on 2021-01-10 15:31

from django.db import migrations, models
import users.models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_trackregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(storage=users.utils.OverwriteStorage(), upload_to=users.models.get_user_tracks_path),
        ),
    ]
