# Generated by Django 3.1.3 on 2021-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_auto_20210110_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.FloatField(default=None, null=True),
        ),
    ]
