# Generated by Django 3.1.3 on 2021-01-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_auto_20210111_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.TextField(),
        ),
    ]
