# Generated by Django 3.1.3 on 2021-01-11 16:08

from django.db import migrations, models
import users.models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_auto_20210111_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(max_length=1024, storage=users.utils.OverwriteStorage(), upload_to=users.models.get_user_tracks_path),
        ),
    ]
