# Generated by Django 3.1.3 on 2020-12-14 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True)),
                ('moto', models.CharField(blank=True, max_length=64)),
                ('avatar', models.ImageField(null=True, upload_to=users.models.get_user_avatars_path)),
                ('bg_picture', models.ImageField(null=True, upload_to=users.models.get_user_profile_bg_img_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
