# Generated by Django 3.1.3 on 2020-12-14 16:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to=users.models.get_user_avatars_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bg_picture',
            field=models.ImageField(blank=True, default='', upload_to=users.models.get_user_profile_bg_img_path),
        ),
    ]
