# Generated by Django 3.1.3 on 2020-12-15 19:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201214_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar_placeholder.png', upload_to=users.models.get_user_avatars_path),
        ),
    ]
