# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '__SECRET_KEY__'

ALLOWED_HOSTS = ['__ALLOWED_HOSTS__']

# Flag for local dev HTTPS test
LOCAL_HTTPS_TEST = False

# Database configuration
POSTGRES_HOST = '__POSTGRES_HOST__'
POSTGRES_PORT = 5432
POSTGRES_DB = '__POSTGRES_DB__'
POSTGRES_USER = '__POSTGRES_USER__'
POSTGRES_PASSWORD = '__POSTGRES_PASSWORD__'

# social_django
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '__SOCIAL_AUTH_GOOGLE_OAUTH2_KEY__'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '__SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET__'
SOCIAL_AUTH_FACEBOOK_KEY = '__SOCIAL_AUTH_FACEBOOK_KEY__'
SOCIAL_AUTH_FACEBOOK_SECRET = '__SOCIAL_AUTH_FACEBOOK_SECRET__'

# email
EMAIL_USE_TLS = True
EMAIL_PORT = '__EMAIL_PORT__'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = '__EMAIL_HOST_USER__'
EMAIL_HOST_PASSWORD = '__EMAIL_HOST_PASSWORD__'

# celery
BROKER_PROTOCOL = 'redis'
BROKER_HOST = 'audio-editor-backend-redis'
BROKER_PORT = 6379

CELERY_BROKER_URL = f'{BROKER_PROTOCOL}://{BROKER_HOST}:{BROKER_PORT}'
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# media
PLACEHOLDER_TRACK_FILENAME = 'Apex_-_Inner_Space.mp3'
